### PR TITLE
Anchored Search + Service_BookPriceService

### PR DESCRIPTION
**Pull request by bimusiek**
I started working on
```5.25 Operation: 02.25 Flight Option - Anchored Search (Basic mode)```
however I was not able to test it yet as I am still waiting for `FSParam Gb_AnchoredSearch` to be enabled on my OID 👍 

I will keep this PR open until I can test if it works properly.

### CODE REVIEW

**Comment by DerMika** [comment]
So what's the status on this PR, @bimusiek ?

**Comment by bimusiek** [comment]
@DerMika Hey sorry for so much delay, our OID is still not enabled for anchored search so I have no way of testing this functionality on production or testing env :(

**Comment by bimusiek** [comment]
Hey @DerMika, I've added `Service_BookPriceService` with basic params required to use the endpoint.

**Comment by bimusiek** [comment]
I will fix coveralls soon, but no idea how to configure `Scrutinizer` to make code coverage.

**Comment by bimusiek** [comment]
@DerMika Hey, could you please check? 😃 I am missing documentation for new endpoint only, but will add it when Amadeus team confirms our certification. (As I am sure there will be some changes to the code)

Also, I think we should add to the docs that when downloading WSDL, you have to download version for .NET with some compatibility, otherwise there is name conflict for one of the attributes in WSDLs.

**Comment by DerMika** [comment]
Next time please squash the commit :)

I'm about to release 1.10.0 and it's hard to find out what has changed since the last release due to this PR not being squashed...

**Pull request merged**
