### PR TITLE
Requesting queueList by the degree of urgency(timeMode)

### LINKED ISSUE #326: Problem with the requesting queueList by the degree of urgency(timeMode)
Queue consists from categories. Category has the degree of urgency of the message. The problem is requesting queue messages by the degree of urgency. It has 4 degrees of urgency.

In another words, I need to pass new `Queue` option in a `queueList` request method, which name is `timeMode`(Now the value is equal to 1 by default). In addition, `QueueList` class should be corrected with `date` attribute initialization.

### PR DESCRIPTION
**Pull request by poltaev1993**
Resolves #326

### CODE REVIEW

**Comment by poltaev1993** [comment]
@DerMika , can you look at travis-ci. It fails with php5.4 and php5.5 version.

**Comment by DerMika** [comment]
Can you merge my updated travis.yml and see if that works?

**Comment by poltaev1993** [comment]
> Can you merge my updated travis.yml and see if that works?

Done! It works.

**Comment by poltaev1993** [comment]
@DerMika I am curious, when will it be in release?

**Comment by DerMika** [comment]
Thanks for your contribution!

I'll try to release a (long overdue) 1.8.0 release soon, but you can use `dev-master` in composer.json as of now.

**Pull request merged**
