### PR TITLE
Queue: Defined default queue constants

### PR DESCRIPTION
**Pull request by therealartz**

### CODE REVIEW

**Comment by DerMika** [comment]
I would still like to keep a sample in the docs showing a queue being used by number (e.g. queue 50), so that people know they can either choose one of the default queues by constant or a self-chosen queue by number.

**Comment by therealartz** [comment]
@DerMika I can add simple example

**Comment by DerMika** [comment]
yes, I would like that. Thanks!

**Comment by DerMika** [comment]
Thanks again!

**Pull request merged**
