### PR TITLE
Masterpricer Expert Search

### PR DESCRIPTION
**Pull request by m0veax**
Hi,

i created a base PR so you can see my progress regarding Issue #168.

There are no Unit Tests or Docs added right now. But this is working and returning Results.

I tried to copy only what is needed but i somehow think, maybe the Master Pricer Base Struct could be modified to hold more of the three Master Pricer types?

Any thoughts for me?

Thanks for your fast Support :)

### CODE REVIEW

**Comment by DerMika** [comment]
The first thing I notice is that the request options object `src/Amadeus/Client/RequestOptions/FareMasterPricerExSearch.php` should follow the naming scheme of the other messages and end in "Options" (I know MasterPricerTravelBoardSearch is an exception to that naming scheme, but that was a mistake by me ;) )

Also, it seems to copy a lot of the MasterPricerTravelBoardSearch request options, perhaps you should consider extending FareMasterPricerTbSearch from your new request options message, whichever is most limited. I don't like copy-pasting :)

The same with building the request structure, you seem to have copy-pasted a lot (which is a good start, but I don't want unnecessary copy-pasting in the released version).

And obviously, unittests still need to be added, because I want the library at 100% (minus 1 file which I haven't figured out how to test completely yet).

so, you're off to a good start

**Comment by DerMika** [comment]
Also, `MPBaseOptions` contains all props shared between the MasterPricer call and the `Ticket_CheckEligibility` message, so you can't add anything to `MPBaseOptions` which isn't available in Ticket_CheckEligibility

**Comment by m0veax** [comment]
Thanks for your feedback. I have some other things to solve right now and will try to come back to that soon.

**Comment by DerMika** [comment]
Sure, no rush! I'm already happy you're willing to contribute ;)

**Comment by DerMika** [comment]
Do you plan to continue working on this PR?

**Comment by m0veax** [comment]
Hey,

yeah i want too.

I saw last week, that you changed things in Travelboard Search, so i will have to adapt that stuff too.

**Comment by DerMika** [comment]
It was only a small change, but yes, I merged yet another @bimusiek PR ;)

Let me know if you need any help, I'd really like to have this message in the library too!

**Comment by m0veax** [comment]
Hey there, i was able to normalize most of the things you called for. One call is extending another one and i was able to solve some other things too.

Beside of the missing unit tests, is that ok now?

**Comment by DerMika** [comment]
> What would be the best way to gather the needed XML for a response test?

I usually either make a real call with a message and remove personal info from the response, or just look if I can find a response sample in the docs

I can't do a review now, I'll have to get back to you in a few days when I have access to my computer again.

**Comment by m0veax** [comment]
No hurries, thanks for the advice. I gonna figure out how the unit tests works meanwhile.

Maybe I have some questions regarding the unit tests, because I rarely do this in php. But I guess it won't differ much to other language test environments

**Comment by m0veax** [comment]
Hey Mika,

did you had some time to take a quick look? If my solution is fitting your needs i would take the next steps due to unit testing.

If you don't have some time, that is ok too :)

I just came back to take a look and don't want to pass that much time again :)

**Comment by DerMika** [comment]
Ok, looking good. There are a few small things, like missing docs, and a `use` statement before the namespace declaration (in `Amadeus\Client\RequestOptions\FareMasterPricerTbSearch`) that should be fixed. Also in `MasterPricerExpertSearchConv` there is a `use` statement to a non-existant class.

You can also check the Scrutinizer analysis above to find some of the issues.

So if you can add unittests and documentation, that would be great!

**Comment by m0veax** [comment]
So, i added docs and did all that the CI tests are passing. Next step for me would be adding tests.

If you find anything i need to change, just leave me a message. I am happy that i make slowly progress to finalize all the things :)

**Comment by m0veax** [comment]
Hm, i started adding some tests, if i run then on my machine by:

`./vendor/bin/phpunit --stop-on-failure`

All tests are passing. I can't figure out how to get that coverage clover up running. Do you have any hint for me?

**Comment by m0veax** [comment]
Are the ClientTest.php Methods are autoloading some xml files? I have some trouble there. Would you be up for a short chat on irc or something?

**Comment by DerMika** [comment]
Sorry for the delay. Are you developing on Windows? In that case it could be a problem with case sensitivity (the unittests are ran on a linux box at TravisCI)

**Comment by DerMika** [comment]
You should be able to find an e-mail address in the code, use that to contact me privately ;)

**Comment by therealartz** [comment]
Waaait a minute.

Tests are failed with error 
`Error: Class 'Amadeus\Client\RequestOptions\FareMasterPricerExSearch' not found`
But there is not class `FareMasterPricerExSearch`, there is `FareMasterPricerExSearchOptions`

**Comment by m0veax** [comment]
Thanks for your insights. I will check this up in my Codebase.

Are there any Resources to understand how responses are loaded in the Testframework? That is the Showstopper for me right now. I really want to finish this, but i didn't had the time to get that tests done (the kids needed a bit more attention the lasts weeks and i wanted to serve the attention they need).

Maybe the comment from @therealartz does fix my problem any way. I will try to apply his changes this month.

**Comment by m0veax** [comment]
> Waaait a minute.
> 
> Tests are failed with error
> `Error: Class 'Amadeus\Client\RequestOptions\FareMasterPricerExSearch' not found`
> But there is not class `FareMasterPricerExSearch`, there is `FareMasterPricerExSearchOptions`.
> 
> It's just need to change the class name in the tests and in samples...

Thanks a lot for that! Somewhere i started to rename that and somehow i missed a lot.

So i just have one test that still fails and will investigate further :)

**Comment by therealartz** [comment]
Now the mistake in this line of your test method:

```php
// ClientTest.php

$mockedSendResult->responseXml = 'dummyfarepricemasterpricerexpertsearchresponsemessage';
```

You must specify responseXml to be taken from example response file in this way:

```php
$mockedSendResult->responseXml = $this->getTestFile('fareMasterPricerExpertSearchReply-12.4.txt');
```

Also I want recommend you to change your example response (fareMasterPricerExpertSearchReply-12.4.txt) to be one-lined XML, because 21k added lines confuses 😄

**Comment by m0veax** [comment]
@therealartz appreciated!

Thanks for your hints!

I hopefully get this done within the next two weeks. But real life is a bit demanding the last year.

**Comment by m0veax** [comment]
Well it seems the next two weeks was too optimistic, but i am working on this again. At the moment i have the Problem, that my XML does not generated properly. I am investigating at the moment and hope to find that last bug soon.

**Comment by DerMika** [comment]
Thanks for coming back to finish this :)

**Comment by m0veax** [comment]
Sure, i don't like unfinished things :)

Could you do me a favor and point me to the Class which is responsible for generating XML out of the Request Object?

My Request Objects seems to miss something and i need to debug this.

**Comment by DerMika** [comment]
Well... What this library does: it builds a PHP object through a `Amadeus\Client\Struct\...` message. That object is given to the PHP `\SoapClient` object (through the` php_soap` extension). It's the magic of the \SoapClient which converts the PHP object to an XML document. Unfortunately you have very little control over that. The SoapClient uses the provided WSDL definition for the message to match the PHP object and convert it to XML.

Usually when you are missing an expected part in the XML document, one of these things happened: 

- Something is missing or wrong in the WSDL / XSD definition loaded by the SoapClient
- Your object is missing a parameter or doesn't have the correct name/datatype expected
- the Soapclient somehow can't decide which definition to use when decoding part of your object, in that case providing it with a custom `ClassMap` can help (https://stackoverflow.com/questions/29800939/advantage-of-php-soapclient-classmap)

So if you suspect there is a mismatch between your object and the WSDL definition, you may try these things: 

- double check your object, did you name every property correctly, does it contain the expected value
- try to hack the WDL / XSD into coercion 
- let Amadeus know the WSDL seems broken, they may know of the issue and provide you with an updated WSDL
- add a map of WSDL/ XSD namespace definitions --> PHP objects to the ClassMap (https://github.com/amabnl/amadeus-ws-client/blob/master/src/Amadeus/Client/Session/Handler/Classmap.php) 
- if you're really determined, you can go debug the php soapclient to see why it does what it does. I've never ventured into that territory yet myself...

**Comment by m0veax** [comment]
Very helpfull, thanks for your input!

**Comment by m0veax** [comment]
So, due to your informations i was able to trace down, that my code generates valid SOAP Requests.

I tested the library against the API too and get valid results. So i am doing something wrong in `ClientTest.php` itself. I gonna dig down that path now.

**Comment by therealartz** [comment]
I had a free hour and I decided to help you.

Found a mistake in test set up.

Could you please give me access to push in your fork?

**Comment by m0veax** [comment]
@therealartz I granted push permissions for you.

I am looking forward to see your changes. Guess I can learn a thing there :)

**Comment by m0veax** [comment]
@therealartz big thanks! I guess I would have spend some working days to find this, since tests are not my daily business yet. But I started to improve my knowledge there already.

@DerMika is this mergable or do we need some more changes :)

**Comment by DerMika** [comment]
I will review tonight...

**Comment by m0veax** [comment]
No hurry :) I just have been happy about this solution

**Comment by m0veax** [comment]
Hey Mika,

anything you need me to do here?

I don't want to hurry you up, but i have some spare time this weekend and would be able to investigate :)

**Comment by DerMika** [comment]
Ok, finally going to merge this. Sorry it took so long!

And thanks for your contribution, much appreciated!

**Pull request merged**
