### PR TITLE
Allow filter by location without limit to airport or city

### PR DESCRIPTION
**Pull request by joseayram**
Hello!

Currently I am develop a project that involve the MasterPricerTravelBoardSearh and MasterPricerCalendar messages and I'm limited at the moment of filter by location without specify city or airport.

The consultant team of Amadeus said me that I need to filter the search without this limitation to get more results.

Adding «**all**» as a third parameter for this option, we can filter by city and airport in the same time.

```
$opt = new FareMasterPricerTbSearch([
        'nrOfRequestedResults' => 10,
        'nrOfRequestedPassengers' => 1,
        'passengers' => [
            new MPPassenger([
                'type' => MPPassenger::TYPE_ADULT,
                'count' => 1
            ]),
        ],
        'itinerary' => [
            new MPItinerary([
                'departureLocation' => new MPLocation(['all' => 'MVD']),
                'arrivalLocation' => new MPLocation(['all' => 'MIA']),
                'date' => new MPDate([
                    'dateTime' => new \DateTime('2021-09-15T10:00:00+0000', new \DateTimeZone('UTC')),
                    'timeWindow' => 5,
                    'rangeMode' => MPDate::RANGEMODE_MINUS_PLUS,
                    'range' => 1
                ])
            ]),
            new MPItinerary([
                'departureLocation' => new MPLocation(['all' => 'MIA']),
                'arrivalLocation' => new MPLocation(['all' => 'MVD']),
                'date' => new MPDate([
                    'dateTime' => new \DateTime('2021-09-30T18:00:00+0000', new \DateTimeZone('UTC')),
                    'timeWindow' => 5,
                    'rangeMode' => MPDate::RANGEMODE_PLUS,
                    'range' => 1
                ])
            ])
        ]
    ]);
```

### CODE REVIEW

**Comment by DerMika** [comment]
Can you please also add a sample to the docs at `docs/samples/masterpricertravelboard.rst`?

**Comment by joseayram** [comment]
> Can you please also add a sample to the docs at `docs/samples/masterpricertravelboard.rst`?

Ready! I added a sample to the end of file. Let me know.

Thanks.

**Comment by joseayram** [comment]
Hello @DerMika! How are you? Is it ok the fix to this PR or Is it missing something more? Thanks

**Comment by DerMika** [comment]
can you resolve the conflict so we can get this PR merged?

**Pull request merged**
