### PR TITLE
commas missing

### PR DESCRIPTION
**Pull request by arosha445**
Fixed some typos

### CODE REVIEW

**Comment by DerMika** [comment]
Thanks for contributing!

**Comment by arosha445** [comment]
You welcome. I guess no one has done the Soap Header 2 example before.

**Comment by DerMika** [comment]
It's possible. They don't provide Soap Header 2 WSAP's to customers anymore usually, there must be a special usecase you're using this library in 2018 with a SoapHeader 2 WSAP? ;)

**Comment by arosha445** [comment]
Actually it was because of the [issue](https://github.com/amabnl/amadeus-ws-client/issues/151).
I thought a Header change might help. 😄

**Pull request merged**
