### PR TITLE
Integration of Service_StandaloneCatalogue Message

### PR DESCRIPTION
**Pull request by arvind-pandey**
Hi DerMika,
Very Good Morning!
I am sending you pull request for new message Service_StandaloneCatalogue.
Please review this and let me know if anything need to do from my side.

### CODE REVIEW

**Comment by DerMika** [comment]
Thanks, I will check this weekend. Sorry for the delay.

**Comment by DerMika** [comment]
Well it seems like you have made some kind of change to every single file in this repository. That will have to be undone certainly.

**Comment by DerMika** [comment]
Please look here: https://stackoverflow.com/questions/1257592/how-do-i-remove-files-saying-old-mode-100755-new-mode-100644-from-unstaged-cha

**Comment by DerMika** [comment]
And the reason why the unittests are failing is because of the classes that are not in capital letters. You've also broken a few unittests for Service_IntegratedPricing and Service_IntegratedCatalogue bcause of that.

**Comment by DerMika** [comment]
If you can fix those issues, the rest of your PR looks very good!

**Comment by arvind-pandey** [comment]
Hi, I am looking into changes suggested by you, will come back.

**Comment by arvind-pandey** [comment]
Many files are showing in file change list that is not even change by me, hence I am closing this pull request and will send fresh pull request

**Comment by DerMika** [comment]
Okay, thanks!

**Pull request closed without merging**
