### PR TITLE
New messages: DocRefund_IgnoreRefund, Ticket_ProcessETicket, Ticket_InitRefund, Ticket_IgnoreRefund, Ticket_ProcessRefund

### PR DESCRIPTION
**Pull request by bimusiek**
Hey, I have implemented 2 new messages.

However, Ticket_ProcessETicketReply` has status `UNKNOWN` and I have no idea how to fix it :|
Any help? :)

### CODE REVIEW

**Comment by DerMika** [comment]
Probably because you named the response handler `HandleProcessETicket.php` instead of `HandlerProcessETicket.php`?

You also still need a unittest for testing the response handlers, but I suppose that's still work in progress?

**Comment by bimusiek** [comment]
Hey @DerMika ! :)
Almost done, however I still have a problem with new ATC refund endpoints.

The lib sends body as:
```xml
...
xmlns:ns1="http://xml.amadeus.com/2010/06/TicketGTP_v2"
...
		<ns1:AMA_TicketInitRefundRQ>
			<ns1:Contracts>
				<ns1:Contract Number="1255118024054"/>
			</ns1:Contracts>
			<ns1:ActionDetails>
				<ns1:ActionDetail Indicator="ATC"/>
			</ns1:ActionDetails>
		</ns1:AMA_TicketInitRefundRQ>
```

Amadeus replies with an error. 

I have got from Amadeus how it should be sent:
```xml
<AMA_TicketInitRefundRQ xmlns="http://xml.amadeus.com/2010/06/TicketGTP_v2" Version="2.000">
    <Contracts>
        <Contract Number="1255118024054" />
    </Contracts>
    <ActionDetails>
      <ActionDetail Indicator="ATC" />
    </ActionDetails>
</AMA_TicketInitRefundRQ>
```

Any idea how I can add these parapeters to the message node? At least I would try with `version` to see if this helps.

**Comment by DerMika** [comment]
Sounds like the only thing you're missing is the Version attribute. 

The fact that the namespace is defined differently (ns1 prefix or xmlns) shouldn't make any differece in how the message is processed on Amadeus' servers.

I think you should be able to define a property `Version` in the class that gets converted to AMA_TicketInitRefundRQ (which seems to be `Amadeus\Client\Struct\Ticket\InitRefund `) and if the XSD of that message is correct, it should be converted to an XML attribute. 

I think.

Can you try that first?

**Comment by bimusiek** [comment]
@DerMika It worked 👍 Thanks a lot for help! 
I guess to fix coverages I need to add some more tests... will do this week. I have to work now on ATC_Refund implementation

**Comment by bimusiek** [comment]
There is still one issue with parsing xml response.

What is returned by Amadeus:
```xml
<att:MonetaryInformations>
  <att:MonetaryInformation Amount="112000" CurrencyCode="GBP" DecimalPlaces="2" Qualifier="B"/>
  <att:MonetaryInformation Amount="0" CurrencyCode="GBP" DecimalPlaces="2" Qualifier="RFU"/>
  <att:MonetaryInformation Amount="112000" CurrencyCode="GBP" DecimalPlaces="2" Qualifier="FRF"/>
  <att:MonetaryInformation Amount="134741" CurrencyCode="GBP" DecimalPlaces="2" Qualifier="RFT"/>
  <att:MonetaryInformation Amount="22741" CurrencyCode="GBP" DecimalPlaces="2" Qualifier="TXT"/>
  <att:MonetaryInformation Amount="22741" CurrencyCode="GBP" DecimalPlaces="2" Qualifier="TP"/>
  <att:MonetaryInformation Amount="0" CurrencyCode="GBP" DecimalPlaces="2" Qualifier="NRC"/>
  <att:MonetaryInformation Amount="134741" CurrencyCode="GBP" DecimalPlaces="2" Qualifier="RFA"/>
  <att:MonetaryInformation Amount="0" CurrencyCode="GBP" DecimalPlaces="2" Qualifier="RUA"/>
</att:MonetaryInformations>
```
And this is how the object looks like 😢 
screenshot 2018-04-18 11 39 44

Any idea how to properly parse it? @DerMika

**Comment by bimusiek** [comment]
@DerMika Any idea about `MonetaryInformation`? 🙏

**Comment by DerMika** [comment]
Not yet i'm afraid, It's likely some mismatch between the Response message and the XSD. I'd have to look at the entire XSD and imported XSD's to figure it out. 

But I had a (possibly) similar issue while trying to implement Hotel messages, and I never found out what the problem was.  Or how to fix it.

See https://github.com/amabnl/amadeus-ws-client/issues/70#issuecomment-297655967

**Comment by DerMika** [comment]
Perhaps, and if not, the other nasty workaround would be to load the raw XML response and work with that... 

Is your PR done now?

**Comment by bimusiek** [comment]
Yes.
I have tested all endpoints with PDT env. (`DocRefund_IgnoreRefund` and all new `Ticket_`)
Thus so many changes to handlers for `Ticket_`

**Comment by DerMika** [comment]
Well, thanks a lot for another great contribution! :)

**Pull request merged**
