### PR TITLE
Supporting of stockProviderDetails parameter is added to InitRefund 

### PR DESCRIPTION
**Pull request by poltaev1993**
Supporting of stockProviderDetails parameter is added to InitRefund.

### CODE REVIEW

**Comment by poltaev1993** [comment]
Hello, @DerMika, can you consider this pull request?
It has little changes of InitRefund. I have just added declaration of stockProviderDetails parameter. But it's important in refunding tickets, which were issued through airline stock provider.  

And sorry for asking, can you release it as patch release after checking pull request?

**Comment by DerMika** [comment]
Allright, looks good to me

**Comment by poltaev1993** [comment]
Thanks @DerMika! Can you tell when are you going to release it?

**Comment by DerMika** [comment]
Just released version 1.9.0!

**Pull request merged**
