### PR TITLE
Ticket process eticket response error handling

### PR DESCRIPTION
**Pull request by suiram2010**
@DerMika please hava a look some minor errorcode handling for Ticket_ProcessETicketReply.

### CODE REVIEW

**Comment by DerMika** [comment]
@bimusiek is this going to break something for you?

**Comment by suiram2010** [comment]
@DerMika are there any updates on this pull request or is there something that blocks the request, that need to be changed ? 
Thank you.

**Comment by DerMika** [comment]
Since we're not getting feedback grom @bimusiek , I guess nothing else is blocking this PR. I'm going to merge it.

**Comment by bimusiek** [comment]
Hey @DerMika, this looks good. It wouldnt break anything. 

I somehow missed notifications from github and just saw a mention.

**Pull request merged**
