### PR TITLE
Air_SellFromRecommendation flight type details attribute

### PR DESCRIPTION
**Pull request by therealartz**
- Added `$flightTypeDetails` property of SellFromRecommendation segment `Amadeus\Client\RequestOptions\Air\SellFromRecommendation\Segment`
- Added test SellFromRecommendation with local availability 
- Selling connecting segments with the slice and dice option docs example (similar to Amadeus Extranet example)
- Added FlightTypeDetails indicator constants of all possible values

### CODE REVIEW

**Comment by DerMika** [comment]
One change I'd like to see: The `FlightTypeDetails ` constants should also be defined in the RequestOptions _(and you should use the constants from the RequestOptions that class in the documentation)_.

I realise this is pretty much just copy-paste, but I don't want people to have to use the `Amadeus\Client\Struct` namespace _at all_ when using the library. That is "internal kitchen".

**Comment by therealartz** [comment]
Define constants at `Amadeus\Client\RequestOptions\Air\SellFromRecommendation\Segment`?

**Comment by DerMika** [comment]
Yes, sounds good!

**Comment by DerMika** [comment]
Thanks again for the contribution!

**Comment by DerMika** [comment]
Version 1.7.0 has just been released!

**Pull request merged**
