### PR TITLE
Implementation of ZAP-Off and accountCode in Queue_List

### PR DESCRIPTION
**Pull request by techork**
Implementation of ZAP-Off for PricePnrWithBookingClass
Queue_List add accountNumber to the request
Implementation of Fare Family per segments (possibility to add fare families per segments)

### CODE REVIEW

**Comment by techork** [comment]
@DerMika Is there a wai to pass Scrutinizer php56 module test? I testet on master pranch and it also fails? Thank You.

**Comment by DerMika** [comment]
I will have a look when I have some time...

**Comment by techork** [comment]
@DerMika  can you have a look at this pull request, I merged with the latest changes from master and passed the checks again

**Comment by DerMika** [comment]
Losing some coverage in `src/Amadeus/Client/Struct/Pnr/AddMultiElements/DataElementsIndiv.php` - can you fix that?

**Comment by DerMika** [comment]
and in the future please provide a separate pull request for each individual change you make

**Comment by techork** [comment]
@DerMika thank you for pointing to errors I made. Please have a look again at the fixes I made. Thank you

**Comment by DerMika** [comment]
https://coveralls.io/builds/31083083 Coveralls still reporting coverage dropped in that file

**Comment by techork** [comment]
@DerMika  Sorry fixed my errors by as I see re remaining errors deals to Ticket_ATCShopperMasterPricerCalendar not implemented by me, my branch has nothing assotiated with Ticket_ATCShopperMasterPricerCalendar

**Comment by DerMika** [comment]
i will check it

**Comment by DerMika** [comment]
yeah I apparently merged a PR which didn't have 100% coverage, shame on me

**Comment by DerMika** [comment]
Would you please add all changes in this PR to the CHANGELOG.MD file?

**Comment by techork** [comment]
@DerMika  updated the CHANGELOG.MD.
Thnak you.

**Comment by DerMika** [comment]
looks like you have a merge conflict. I updated the readme yesterday when I published version 1.10.0. Can you resolve the conflict please?

**Comment by DerMika** [comment]
i fixed the conflict

**Comment by techork** [comment]
@DerMika  Thank you, sorry I was away ffrom PC

**Comment by DerMika** [comment]
No problem!

**Comment by DerMika** [comment]
Thanks for contributing! (and sorry it took me such a long time)

**Pull request merged**
