### PR TITLE
Added support for Fee Options in Fare_MasterPricerTravelBoardSearch

### PR DESCRIPTION
**Pull request by zervel**
Added 2 option in MasterPricer:
5.69 Operation: 06.3 Fee Option - Sorting with/without Fees
5.71 Operation: 06.5 Fee Option - Add/Exempt airline ticketing fees by sub-
code

### CODE REVIEW

**Comment by DerMika** [comment]
Hi, 

Thanks for contributing!

The only problem I see is that the request options object `MPFeeOption` seems to be overly complex. 

It has always been a goal of this library to make building the request as easy as possible, and for the `MPFeeOption` as you've built it now, I wonder what can be done to make it simpler to use. 

It doesn't have to match the XML message request structure, in fact if you can make it easier to use (while still providing all possibilities provided by Amadeus' API), I would prefer that. 

For example: 
- constant values which only have one option should not have to be provided by the user of this library, I prefer if such values are automatically filled (e.g. `MonetaryDetails::TYPE_QUALIFIER_ASSOCIATED_FEE`)
- a level of XML nodes which is redundant for providing options should not be necessary to put in the request options, as it requires extra work by users of the library to implement. 

So, can you please try to simplify the request options as much as possible (while keeping all options open that are possible according to the documentation)?

**Comment by zervel** [comment]
Hi,
thank you for your feedback.
i simplified the fee option request.

**Comment by DerMika** [comment]
Looks much better! I will check this weekend if the request built matches the Amadeus docs, and then I'll merge. 

One small error I noticed: in `Amadeus\Client\Struct\Fare\MasterPricer\MonetaryDetails` you're not passing the `location` property of `MonetaryDetailsRequest`.

**Comment by DerMika** [comment]
Thanks again for your contribution!

**Comment by zervel** [comment]
Sure, you can add my name i forgot to add this :)

**Comment by DerMika** [comment]
Version 1.7.0 has just been released with this PR included!

**Pull request merged**
