### PR TITLE
Implementation of FOP_ValidateFOP

### PR DESCRIPTION
**Pull request by bimusiek**
Started working on implementation of `FOP_ValidateFOP`. 

I will test it on our system, add some documentations and then it should be ready to release. 👍

### CODE REVIEW

**Comment by bimusiek** [comment]
@DerMika Any ideas why Travis fails? 
Locally I am getting `OK (604 tests, 5233 assertions)` 😞

**Comment by DerMika** [comment]
The Travis build fails with a unit test on the response handler, getting unknown instead of ERR  status

**Comment by DerMika** [comment]
```
Time: 23.31 seconds, Memory: 40.00MB
There was 1 failure:
1) Test\Amadeus\Client\ResponseHandler\BaseTest::testCanHandleFopValidateFopErrorResponse
Failed asserting that two strings are equal.
--- Expected
+++ Actual
@@ @@
-'ERR'
+'UNKNOWN'
/home/travis/build/amabnl/amadeus-ws-client/tests/Amadeus/Client/ResponseHandler/BaseTest.php:1427
FAILURES!
Tests: 604, Assertions: 5228, Failures: 1.
```

**Comment by bimusiek** [comment]
@DerMika I see the travis status, however I cannot reproduce locally. All tests pass on my machine :( And I made sure to parse these errors properly (based on CreateFOP)

**Comment by DerMika** [comment]
Posting this while on vacation by the way ;)

**Comment by bimusiek** [comment]
@DerMika GO AWAY! 🌞 GET SOME REST!

**Comment by DerMika** [comment]
Did you commit and push the XML sample message?

**Comment by DerMika** [comment]
I would also advise you to remove all personally identifiable information from your sample message.

**Comment by bimusiek** [comment]
There is only a name, I don't care about it :) Credit Card is dummy one.

I still have no clue why the tests fail on Travis. My guess is that `HandlerValidateFOP` is not called on Travis somehow. Could case sensitivity be an issue?

**Comment by DerMika** [comment]
Yes, those Travis builds are running on a Linux platform

**Comment by bimusiek** [comment]
Found the issue:
```
-        $result = $respHandler->analyzeResponse($sendResult, 'Fop_ValidateFOP');
+        $result = $respHandler->analyzeResponse($sendResult, 'FOP_ValidateFOP');
```

**Comment by DerMika** [comment]
Thanks a lot for your contribution!

**Pull request merged**
